# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
a=float(input("Введите первое число:"))
b=float(input("Введите второе число:"))
print("{:.4f} + {:.4f} = {:.4f}".format(a,b,(a+b)))
print("{:.4f} - {:.4f} = {:.4f}".format(a,b,(a-b)))
print("{:.4f} * {:.4f} = {:.4f}".format(a,b,(a*b)))
if (b!=0): print("{:.4f}/{:.4f} = {:.4f}".format(a,b,(a/b)))
else: print("Деление на ноль неопределено!")