# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

k = int(input("Введите номер дня в году (1 <= k <= 365): "))
d = int(input("Введите номер дня недели, на которую приходится 1 января (1 - понедельник, 2 - вторник, ..., 7 - воскресенье): "))
weekday = (d + k - 2) % 7 + 1
print("День", k, "в году начинающемся с дня", d, "приходится на день недели",weekday)