# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

col = 5
row = 10
cell_number=int(input("Введите порядковый номер ячейки: "))
if cell_number > col*row:
  print("Ячейки с таким номером нет")
else:
  cell_row = (cell_number-1) // col + 1
  cell_col = (cell_number-1) % col + 1
  print(f'Ячейка {cell_number} находится в {cell_row}-й строке в {cell_col}'\
  '-м столбце.')