# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
a=float(input("Введите a: "))
b=float(input("Введите b: "))
if (a==0):
  if (b!=0):
    print("Решений нет!")
  else:
    print("x - любое число!")
else:
  x=(-1*b)/a
  print("x = %.4f" %x)