# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZkqU7XpabGhqXhxbxulsO9ie6FxARfd
"""

numbers = [50, 10]
for n in numbers:
    print(n)