# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

import math
n=int(input("Введите натуральное число n > 1: "))
x=float(input("Введите вещественное число x (-1<x<=1): "))
if n<=1:
  print(f'{n}<=1!')
else:
  sum = x
  prod = x
  for i in range(2,n+1):
    prod *= -x
    sum += prod / i
  print("x-x^2/3+ ... +(-1)^(n+1)*x^n/n = %.6f" %sum)
print("ln(1+x) = %.6f." %math.log(x+1))

