# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZkqU7XpabGhqXhxbxulsO9ie6FxARfd
"""

numbers = input("Введите три любых числа через пробел: ")
print('  '.join(numbers.split()))