# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
print("Введите координаты точек")
x1=float(input("x1 = "))
y1=float(input("y1 = "))
x2=float(input("x2 = "))
y2=float(input("y2 = "))
d=math.sqrt((x2 - x1)**2+(y2 - y1)**2)
print("Расстояние между точками = %.4f." %d)