# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

flag=1
while (flag==1):
  monitor_price = float(input("Стоимость монитора, руб.: "))
  block_price = float(input("Стоимость системного блока, руб.: "))
  keypad_price = float(input("Стоимость клавиатуры, руб.: "))
  mouth_price = float(input("Стоимость мыши, руб.: "))
  number = int(input("Количество компьютеров в заказе: "))
  purchase_cost=number*(monitor_price+block_price+keypad_price+mouth_price)
  print("Стоимость заказа: %.2f" %purchase_cost)
  flag=int(input("Расчитать еще один заказ? (1 - да, 0 - нет): "))