# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
print("Введите стороны прямоугольника")
a=float(input("a="))
b=float(input("b="))
p=2*a+2*b
c=math.sqrt(a**2+b**2)
print("Периметр прямоугольника = %.4f\n" %p,\
      "Диагональ прямоугольника = %.4f" %c,sep='')