# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n=int(input("Введите натуральное число n: "))
sum = 0
for i in range(n, 2*n + 1):
  sum += i**2
print(f'Сумма квадратов чисел от {n} до {2*n} равна {sum}')

