# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

import random

def print_vec(vec, format_str): # vec - массив, format_str - формат вывода
  print("[", end='')
  for i in range(len(vec)-1):
    if i%10!=9:
      print(format_str.format(vec[i]),end=', ')
    else:
      print(format_str.format(vec[i]),",\n",end='',sep='')
  print(format_str.format(vec[len(vec)-1]),"]",sep='')

n=int(input("Введите длину массива: "))
#а
a = float(input("Введите первый член арифметической прогрессии: "))
p = float(input("Введите разность арифметической прогрессии: "))
x=[a]
for i in range(1,n):
  x.append(a+i*p)
print(f'Массив из первых {n} членов арифматической прогрессии:', end='\n', sep='')
print_vec(x,"{:.4f}")

#б
x=[1,1]
for i in range(2,n):
  f = x[i-1]+x[i-2]
  x.append(f)
print(f'Массив из первых {n} чисел Фибоначчи:', end='\n', sep='')
print_vec(x,"{}")

