# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

import math
n=int(input("Введите натуральное число n > 1: "))
x=float(input("Введите вещественное число x: "))
if n<=1:
  print(f'{n}<=1!')
else:
  sum = 1
  prod = 1
  for i in range(1,n+1):
    prod *= x/i
    sum += prod
  print("1+x+x^2/2! ... +x^n/n! = %.6f" %sum)
print("exp(x) = %.6f." %math.exp(x))

