# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

flat_number = int(input('Введите номер квартиры: '))
if flat_number < 1 or flat_number > 15:
    print('Такого номера квартиры в подъезде нет')
else:
    floor = (flat_number - 1) // 3 + 1
    print(f'Квартира № {flat_number} находится на {floor} этаже')