# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

def Factorial(n): #Вычисляем n!
  if n==1:
    return 1
  else:
    return n*Factorial(n-1)

n = int(input("Введите n: "))
print("n! =", Factorial(n))

