# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

flag=1
while (flag==1):
  v1=float(input("Скорость первого автомобиля, км/ч: "))
  v2=float(input("Скорость второго автомобиля, км/ч: "))
  if (v1<=v2):
    print("Скорости автомобилей не соответствуют условию задачи!")
  else: flag=0
S=float(input("Расстояние между автомобилями, км,  при t=0: "))
t=40/60
S=S+t*(v1-v2)
print("Расстояние между автомобилями при t = 40 мин.: %.2f км" %S)