# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

seat_number = int(input("Введите номер места: "))
if seat_number > 36:
    print("Такого места не существует")
else:
    coupe_number = (seat_number - 1) // 4 + 1
    print("Место номер", seat_number, "находится в купе номер", coupe_number)