# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
S=float(input("Введите площадь государства (кв.км.)): "))
Population=float(input("Введите количество жителей (тыс. чел.): "))
Pop_density=Population*1000/S
print("Плотность населения равна %.0f чел. на кв.км." %Pop_density)