# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZkqU7XpabGhqXhxbxulsO9ie6FxARfd
"""

pi = 3.1415926
print(round(pi, 3))