# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

d=2
n = int(input("С начала года 1990 года прошло месяцев: "))
x= n % 12 + 1
month = {1 :'январь', 2 :'февраль', 3: 'март', 4:'апрель',  5:'май', 6:'июнь',\
  7:'июль', 8:'август', 9:'сентябрь', 10:'октябрь', 11:'ноябрь', 12:'декабрь'}
print(f'Идет месяц {month.get(x)}')