# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
m=float(input("Введите массу тела: "))
V=float(input("Введите объем тела: "))
ro=m/V
print("Плотность тела %.5f" %ro)