# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

V1 = float(input("Введите объем первого тела, V1 = "))
m1 = float(input("Введите массу первого тела, m1 = "))
V2 = float(input("Введите объем первого тела, V2 = "))
m2 = float(input("Введите массу первого тела, m2 = "))
ro1 =m1 / V1
ro2 =m2 / V2
if  ro1==ro2:
  print("Плотности тел равны!")
else:
  if ro1>ro2:
    print("Плотность первого тела больше!")
  else:
    print("Плотность второго тела больше!")

