# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
r1=float(input("Радиус r1: "))
r2=float(input("Радиус r2: "))
if (r1==r2): print("Площадь кольца равна 0!")
else:
  s=abs(math.pi*(r1**2 - r2**2))
  print("Площадь кольца = %.4f" %s)