# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n=input("Введите трехзначное число: ")
if len(n)!=3:
  print("Введенное число не трехзначное!")
else:
  ones = int(n[2]) #число единиц
  tens = int(n[1]) # число десятков
  hundreds = int(n[0]) # число сотен
  sum = ones + tens + hundreds
  prod = ones * tens * hundreds
  print(f'В числе {n} {tens} десятков и {ones} единиц.')
  print(f'Сумма цифр числа {n} равна {sum}.')
  print(f'Произведение цифр числа {n} равно {prod}.')