# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

import math

x = float(input("Введите значение x: "))
if math.sin(x) < 0:
    k = x ** 2
else:
    k = abs(x)

if k < x:
    f = k * x
else:
    f = k + x
print("f(%.2f)"%x,"= %.4f"%f)

