# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

days = int(input("Введите количество дней: "))
weeks = days // 7
print("За", days, "дня(ей) прошло", weeks, "полных недель.")