# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

distance = int(input("Введите расстояние в сантиметрах: "))
meters = distance // 100 # вычисляем полные метры
print("Число полных метров: ", meters) # выводим результат