# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

import math
n=int(input("Введите натуральное число n: "))
sum = 0
sign = 1
for i in range(1,n+1):
  sum += sign / i
  sign *= -1
f = math.log(2)
print("1 - 1/2 + 1/3 + ... + 1/n =%.6f" %sum)
print("ln 2 = %.6f" %f)

