# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZkqU7XpabGhqXhxbxulsO9ie6FxARfd
"""

nums = []
for i in range(4):
    num = input("Введите число: ")
    nums.append(num)

print(" ".join(nums))