# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

users = {12345: 'Петров', 11111 : 'Васечкин'}
flag = 1
while flag == 1:
  password = int(input("Введите пароль: "))
  if password not in users.keys():
    print("Пароль неверный!")
  else:
    for i in users.keys():
      if password == i:
        print(f'Здравствуйте, {users[i]}!')
        flag = 0

