# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n=input("Введите трехзначное число: ")
if len(n)!=3:
  print("Введенное число не трехзначное!")
  if len(n)>3:
    m=int(n[::-1])
    print(f'Число {n} при прочтении справа налево: {m}.')
else:
  m=int(n[2]+n[1]+n[0])
  print(f'Число {n} при прочтении справа налево: {m}.')