# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
print("Введите координаты точек")
x1, y1 = float(input("x1 = ")), float(input("y1 = "))
x2, y2 = float(input("x2 = ")), float(input("y2 = "))
x3, y3 = float(input("x3 = ")), float(input("y3 = "))
a=math.sqrt((x2-x1)**2+(y2-y1)**2)
b=math.sqrt((x3-x2)**2+(y3-y2)**2)
c=math.sqrt((x3-x1)**2+(y3-y1)**2)
if (a+b<=c) or (a+c<=b) or (b+c<=a):
  print("Точки не задают треугольник!")
else:
  p=a+b+c
  d=p/2
  s=math.sqrt(d*(d-a)*(d-b)*(d-c))
  print("Периметр = %.5f" %p, "и площадь = %.5f" %s )