# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
print("Введите координаты точек A(x1,y1), B(x2,y2), C(x3,y3), D(x4,y4)")
x1, y1 = float(input("x1 = ")), float(input("y1 = "))
x2, y2 = float(input("x2 = ")), float(input("y2 = "))
x3, y3 = float(input("x3 = ")), float(input("y3 = "))
x4, y4 = float(input("x4 = ")), float(input("y4 = "))
AB = math.sqrt((x2-x1)**2+(y2-y1)**2)
BC = math.sqrt((x3-x2)**2+(y3-y2)**2)
CD = math.sqrt((x4-x3)**2+(y4-y3)**2)
AD = math.sqrt((x4-x1)**2+(y4-y1)**2)
AC = math.sqrt((x1-x3)**2+(y1-y3)**2) #диагональ AC
p1 = (AB+BC+AC)/2
p2 = (AC+AD+CD)/2
s = math.sqrt(p1*(p1-AB)*(p1-BC)*(p1-AC))+math.sqrt(p2*(p2-AC)*(p2-AD)*(p2-CD))
print("Площадь = %.4f" %s )