# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

p = int(input("Введите количество секунд, прошедших с начала суток: "))
hours = p // 3600
minutes = (p % 3600) // 60
seconds = (p % 3600) % 60
print(f'С начала суток прошло полных часов: {hours}. ' )
print(f"С начала очередного часа прошло полных минут: {minutes}.")
print(f"С начала очередной минуты прошло полных секунд: {seconds}.")