# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n=int(input("Введите двузначное число: "))
if (n > 99) or (n<10):
  print("Введенное число не двузначное!")
else:
  sum =  n // 10 + n % 10
  print(f'Сумма цифр числа {n} равна {sum}.')