# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZkqU7XpabGhqXhxbxulsO9ie6FxARfd
"""

print("{0} {1} {2}".format(31, 18, 79))