# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

def Fibonacci(n): #Вычисляем n-е число Фибоначчи
  if n==1 or n==2:
    return 1
  else:
    return Fibonacci(n-1)+Fibonacci(n-2)

n = int(input("Введите n: "))
print(n, "первых чисел Фибоначчи:")
for i in range(1,n+1):
    print(Fibonacci(i), end=' ')

