# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
R=6350
h=float(input("Введите высоту точки наблюдения в километрах: "))
d=math.sqrt((R+h)**2-(R**2));
print('Расстояние до линии горизонта %.4f км'%d)