# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

# арифметическое решение
n=int(input("Введите трехзначное число: "))
if (n > 999) or (n<100):
  print("Введенное число не трехзначное!")
else:
    ones = n % 10 #число единиц
    n = n // 10
    hundreds = n // 10 # число сотен
    tens = n % 10 # число десятков
    print(f'{hundreds}, {tens}, {ones}.')
#другое решение
n=input("Введите трехзначное число: ")
if len(n)!=3:
  print("Введенное число не трехзначное!")
else: print(f'{n[0]}, {n[1]}, {n[2]}.')