# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

km_in_hour = 1000/3600
v1 = float(input("Введите скорость в км/ч, v1 = ")) * km_in_hour
v2 = float(input("Введите скорость в м/с, v2 = "))
if  v1==v2:
  print("Скорости равны!")
else:
  if v1 > v2:
    print("Скорость v1 больше!")
  else:
    print("Скорость v2 больше!")

