# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n=int(input("Введите натуральное число n > 1: "))
if n<=1:
  print(f'{n}<=1!')
else:
  sum = 1
  prod = 1
  for i in range(1,n+1):
    prod *= 3
    sum += 1 / prod
  print("1 + 1/3 + ... +1/3^{} = {:.6f}.".format(n, sum))

