# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

flag=1
while flag==1:
  n=input("Введите трехзначное число все цифры которого различны: ")
  if not n.isdigit():
    print("Введено не число!")
  else:
    flag=0
    if len(n)!=3:
      print("Введенное число не трехзначное!")
    else:
        if len(set(n)) != 3: #проверяем все ли цифры различны
          print("Не все цифры различны!")
        else:
          n1=int(f'{n[0]}{n[2]}{n[1]}')
          n2=int(f'{n[1]}{n[0]}{n[2]}')
          n3=int(f'{n[1]}{n[2]}{n[0]}')
          n4=int(f'{n[2]}{n[0]}{n[1]}')
          n5=int(f'{n[2]}{n[1]}{n[0]}')
          n=int(n)
          print(f'Перестановки числа {n}:')
          print(f'{n1}, {n2}, {n3}, {n4}, {n5}.')

