# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import random

def print_matrix(M, format_str): # M - матрица, format_str - формат вывода
  for row in M:
    for col in row:
      print(format_str.format(col),end=' ')
    print()
n=int(input("Введите n: "))
left = random.randint(-9,5)
right = left+random.randint(0,10)
A = [[random.randint(left,right) for j in range(n)] for i in range(n)]
print_matrix(A,"{: }")
#а
max_row = []
for row in A:
  max_row.append(max(row))
print("Максимумы строк: ",max_row)

#б
min_col = []
for j in range(n):
  minim = A[0][j]
  for i in range(1,n):
    if A[i][j] <minim:
      minim = A[i][j]
  min_col.append(minim)
print("Минимумы столбцов:",min_col)
#в
trace = 0
for i in range(n):
  trace += A[i][i]
print("След матрицы равен:", trace)