# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

#а
print("5 10")
print("7 см")
#б
t = int(input("Введите значение t: "))
v = int(input("Введите значение v: "))
print(100, t, sep=" ")
print(1949, v, sep=" ")
#в
x = int(input("Введите значение x: "))
y = int(input("Введите значение y: "))
print(x, 25, sep=" ")
print(x, y, sep=" ")