# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

print("Введите длины сторон прямоугольного параллелепипеда:")
a=float(input("a = "))
b=float(input("b = "))
c=float(input("c = "))
print("V = %.4f" %(a*b*c))
print("S_боковая = %.4f" %(2*(a+b)*c))