# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n=int(input("Введите натуральное число n > 2: "))
if n<=2:
  print(f'{n}<=2!')
else:
  sum = 0
  for i in range(2,n+1):
    sum += i / (i+1)
  print("2/3 +  ... + {}/({}) = {:.6f}.".format(n, n+1, sum))

