# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n = input("Введите натуральное число, большее 99: ")
if int(n) < 100:
    print("Число должно быть больше 99.")
else:
    # находим количество десятков
    tens = int(n[len(n)-2])
    # находим количество сотен
    hdrs= int(n[len(n)-3])
    print("Число десятков:", tens)
    print("Число сотен:", hdrs)

