# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
a = float(input("Введите первое число:"))
b = float(input("Введите второе число:"))
x = (abs(a)+abs(b))/2
y = math.sqrt(abs(a*b))
print("Среднее арифметическое %.4f" %x)
print("Среднее геометрическое %.4f" %y)