# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZkqU7XpabGhqXhxbxulsO9ie6FxARfd
"""

name = input("Введите имя: ")  # Запрашиваем имя у пользователя
message = "Привет, {}"  # Создаем шаблон сообщения
print(message.format(name))  # Заменяем {} на введенное имя и выводим сообщение на экран