# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
#а
a=float(input("Введите a: "))
y= math.sqrt((2*a+math.tan(abs(3*a)))/math.e)
print(y)
#б
x=float(input("Введите x: "))
y=math.sin((math.pi+math.sqrt(1+2*x))/abs(7*x))
print(y)