# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import random

def print_vec(vec, format_str): # vec - массив, format_str - формат вывода
  print("[", end='')
  for i in range(len(vec)-1):
    if i%10!=9:
      print(format_str.format(vec[i]),end=', ')
    else:
      print(format_str.format(vec[i]),",\n",end='',sep='')
  print(format_str.format(vec[len(vec)-1]),"]",sep='')

n=random.randint(10,100)
a = random.randint(0,50)
b = a+random.randint(0,50)
x=[]
for i in range(n):
  #добавляем в массив случайное число от a до b
  x.append(random.uniform(a,b))
print_vec(x,"{:.4f}")
#а
print("Максимальный элемент x: %.4f" %max(x))
print("Минимальный элемент x: %.4f" %min(x))
#б
mean = 0
for i in range(n):
 mean += x[i]
mean = mean/n

print("Длина массива {}, элементы между {} и {}.".format(n,a,b))
print("Среднее арифметическое элементов массива равно:%.4f" %mean)
#в
c = float(input("Введите произвольное число c: "))
for i in range(n):
 x[i] *= c
print_vec(x,"{:.4f}")