# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZkqU7XpabGhqXhxbxulsO9ie6FxARfd
"""

number = int(input("Введите целое число: "))
print("Следующее за числом", number, "число -", number + 1)
print("Для числа", number, "предыдущее число -", number - 1)