# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

#а
x = float(input("Введите значение x: "))
if x > 1:
    y = 1
else:
    y = x
print("y(%.2f) ="%x, "%.2f" %y)

#б
x = float(input("Введите значение x: "))
if x > -4:
    y = -4
else:
    y = -x
print("y(%.2f) ="%x, "%.2f" %y)

