# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

N = float(input("Введите начальный размер вклада: "))
r = float(input("Введите процент: r% = "))/100
#а
N_a = N
print("Прирост суммы вклада за 1, 2, ..., 10 месяц: ", end=' ')
for i in range(1,11):
  inc = N_a*r
  N_a += inc
  print("%.2f" %inc, end =' ')
print("\nСумма вклада через 3, 4, ..., 12 месяцев: ", end=' ')
#б
N *= (1+r)**2
for i in range(3,13):
  N *= (1+r)
  print("%.2f" %N, end=' ')

