# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

F=float(input("Температура по шкале Фаренгейта,°F: "))
t=(F-32)*5/9
K=t-273.5
print("Температура по шкале Цельсия: %.2f °C" %t)