# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

floors = 9 # количество этажей в доме
porches = 4 # количество подъездов
flats_on_floor = 6
flats_in_porch = floors * flats_on_floor
n=int(input("Введите номер квартиры: "))
if n > floors * flats_on_floor * porches:
  print("Квартиры с таким номером в доме нет")
else:
  porch_num = (n-1) // flats_in_porch + 1
  floor_number = (n-(porch_num-1)*flats_in_porch-1) // flats_on_floor + 1
  number_on_floor = (n-(porch_num-1)*flats_in_porch-1) % flats_on_floor + 1
  print(f'Квартира {n} находится в {porch_num}-м подъезде, на {floor_number}-м'\
    f' этаже: это {number_on_floor}-я по счету квартира.')