# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

side = 130 # сторона квадрата
width = 543 # ширина прямоугольника
height = 130 # высота прямоугольника

# находим количество квадратов по ширине и высоте
count_width = width // side
count_height = height // side

# общее количество квадратов
count = count_width * count_height

print("Из прямоугольника можно отрезать", count, "квадрата(ов)")