# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n=int(input("Введите натуральное число n>3: "))
if n<=3:
  print(f'{n}<=3!')
else:
  F_1 = 1
  F_2 = 1
  print("Последовательность Фибоначчи:", F_1, F_2, end=' ')
  for i in range(3,n+1):
    F_i = F_2 + F_1
    F_1 = F_2
    F_2 = F_i
    print(F_i,end=' ')
  print("...")

