# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

a = int(input("Введите первое целое число: "))
b = int(input("Введите второе целое число: "))
print(a,"+",b,"=",a+b,end="  ")
print(a,"-",b,"=",a-b,end="  ")
print(a,"*",b,"=",a*b,end="  ")
print(a,"/",b,"=",a/b,end="  ")
print("(",a,"+",b,")/2=",(a+b)/2)