# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n = input("Введите натуральное число, большее 999: ")
if int(n) < 1000:
    print("Число должно быть больше 999.")
else:
    # находим количество сотен
    hdrs = int(n[len(n)-3])
    # находим количество тысяч
    thds = int(n[len(n)-4])
    print("Число сотен:", hdrs)
    print("Число тысяч:", thds)

