# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

mass = int(input("Введите массу в килограммах: "))
centners = mass // 100
print("Число полных центнеров в массе:", centners)