# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

#а
x=float(input("Введите x: "))
y=832+x*(-7+15*x*x)
print("y =%.4f" %y)
#б
a=float(input("Введите a: "))
a *= a
y=-12 + a * (5 + 2 * a)
print("y =%.4f" %y)