# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZkqU7XpabGhqXhxbxulsO9ie6FxARfd
"""

#целые
number = int(input("Введите целое число: "))
print(f"{number} - вот какое число Вы ввели")
#действительные
number = float(input("Введите действительное число: "))
print(f"{number} - вот какое число Вы ввели")