# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

# а)
num = input("Введите четырехзначное число: ")
if len(num)!=4:
  print("Введенное число не четырехзначное!")
else:
  sum_4 = int(num[0]) + int(num[1]) + int(num[2]) + int(num[3])
  print(f"Сумма цифр 4-значного числа {num}: {sum_4}")

# б)
num = input("Введите 5-значное число: ")
if len(num)!=5:
  print("Введенное число не 5-значное!")
else:
  sum_5 = int(num[0]) + int(num[1]) + int(num[2]) + int(num[3]) + int(num[4])
  print(f"Сумма цифр 5-значного числа {num}: {sum_5}")