# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
print("Введите целые a и b")
a=int(input("a = "))
b=int(input("b = "))
x=(a+b)/2
y=math.sqrt(a*b)
print("Среднее арифметическое %.5f" %x)
print("Среднее геометрическое %.5f" %y)