# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

import math
n=int(input("Введите натуральное число n >= 1: "))
if n<1:
  print(f'{n}<1!')
else:
  prod = 1
  for i in range(1,n+1):
    prod *= i
  print("{}! = {:.6f}.".format(n,prod))
# приближение по формуле Стирлинга
fact_n = math.sqrt(2*math.pi*n)*((n/math.e)**n)
print("{}!≈ {:.6f}.".format(n,fact_n))

