# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

#а
print("2", "кг",sep="\t")
print("13","17",sep="\t")
#б
a = int(input("Введите значение a: "))
b = int(input("Введите значение b: "))
print(a, 1, sep="\t")
print(19, b, sep="\t")
#в
x = int(input("Введите значение x: "))
y = int(input("Введите значение y: "))
print(x, y, sep="\t")
print(5, y, sep="\t")