# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n=int(input("Введите двузначное число: "))
if (n > 99) or (n<10):
  print("Введенное число не двузначное!")
  tens = n // 10 # число десятков
  ones = n % 10 #число единиц
  print(f'В числе {n} {tens} десятков и {ones} единиц.')
else:
  tens = n // 10 # число десятков
  ones = n % 10 #число единиц
  print(f'В числе {n} {tens} десятков и {ones} единиц.')