# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

# а)
for i in range(20, 36):
    print(i)

#б)
a = int(input("Введите число a (a<=50): "))
if a>50:
  print(f'{a}>50!')
else:
  for i in range(a, 51):
    print(f'{i}^2 = {i**2}')

#в)

b = int(input("Введите число b>=10: "))
if b<10:
  print(f'{b}<10!')
else:
  for i in range(10, b+1):
    print(f'{i}^3 = {i**3}')

#г)

a = int(input("Введите число a: "))
b = int(input("Введите число b(>=a): "))
if a>b:
  print(f'{a}>{b}!')
else:
  for i in range(a, b+1):
    print(i)

