# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

print("Введите цифры чисел a2a1 и b2b1")
a1 = int(input("Введите a1: "))
a2 = int(input("Введите a2: "))
b1 = int(input("Введите b1: "))
b2 = int(input("Введите b1: "))
if a1<10 and a2<10 and b1<10 and b2<10:
  c1 = (a1+b1)%10
  c2 = (a2+b2+(a1+b1)//10)%10
  c3 = (a2+b2+(a1+b1)//10)//10
  print(f'{a2}{a1} + {b2}{b1} =',int(f'{c3}{c2}{c1}'))
else:
  print("По крайней мере одно из введенных чисел больше 9!")

