# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
x = float(input("Введите x: "))
y = float(input("Введите y: "))
q = 3*math.cos(math.pi * x)-abs(2-y)
z = q + (2+q)/(q**2 + 3) / (1/math.sqrt(q**2+8))
print("z = %.4f" %z)