# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

import math

x = float(input("Введите значение x: "))
a = float(input("Введите значение a: "))
if x>=0:
    y = 1 - math.exp(-a*x)
else:
    y = 0

print("y(%.2f) ="%x, "%.6f" %y)

