# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

t=float(input("Температура,°C: "))
F=t*1.8+32
K=t-273.5
print("Температура по шкале Фаренгейта: %.2f °F" %F)
print("Температура по шкале Кельвина: %.2f K" %K)