# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

a=float(input("Катет a: "))
b=float(input("Катет b: "))
s=a*b/2
print("Площадь треугольника = %.4f" %s)