# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

a=float(input("Введите длину ребра куба: "))
s=4*(a**2)
v=a**3
print("Площадь боковой поверхности куба %.4f\n" %s, "Объем куба %.4f" %v, sep='')