# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
r=float(input("Введите радиус окружности: "))
l=2*math.pi*r
S=math.pi*r**2
print("Длина окружности %.4f\n" %l,"Площадь круга %.4f" %S, sep='')