# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n=input("Введите трехзначное число: ")
if len(n)!=3:
  print("Введенное число не трехзначное!")
  if len(n)>3:
    m=int(f'{n[1]}{n[0]}{n[2:]}')
    print(f'Число {n} '\
    'после того как в нем переставили первую и вторую цифру местами:'\
    f'{m}.')
else:
  m=int(f'{n[1]}{n[0]}{n[2]}')
  print(f'Число {n} после того как в нем переставили первую и вторую цифру местами: {m}.')