# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

candy_price = float(input("Стоимость 1 кг конфет, руб.: "))
cookies_price = float(input("Стоимость 1 кг  печенья, руб.: "))
apple_price = float(input("Стоимость 1 кг яблок, руб.: "))
candy_weight = float(input("Вес конфет, кг: "))
cookies_weight = float(input("Вес печенья, кг: "))
apple_weight = float(input("Вес яблок, кг: "))
purchase_cost=candy_price*candy_weight+cookies_price*cookies_weight+\
apple_price*apple_weight
purchase_weight=candy_weight+cookies_weight+apple_weight
print("Стоимость покупки: %.2f руб." %purchase_cost)
print("Вес покупки: %.3f кг" %purchase_weight)