# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
#а
x=float(input("Введите x: "))
y=float(input("Введите y: "))
z = 5 * x**3 - 7 * x * y - 4 * x**2 - 8 * y - 11
print("z =", z)
#б
a=float(input("Введите a: "))
b=float(input("Введите b: "))
x = 2 * math.pi*(a-b)**3 + 4 * b**2 + 3 * a - 7*math.pi
print("x =", x)