# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

a = int(input("Введите a: "))
b = int(input("Введите b: "))
res = 1 + (a%b) + (b%a)
print(res)

