# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

x=input("Введите трехзначное число: ")
if len(x) != 3 :
  print("Число не трехзначное!")
else:
    n = int(f'{x[2]}{x[:2]}')
    print("Получилось число:", n)

