# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

#для второго варианта нумерации мест
layers = 10 # количество ярусов
sections = 8 # количество секций
cells_on_layer = 15 #количество мест для товаров в одной секции на каждом ярусе
cells_in_section = layers * cells_on_layer
n=int(input("Введите номер места: "))
if n > layers * cells_on_layer * sections:
  print("Места с таким номером на складе нет")
else:
  layer_number = (n-1) % layers  + 1
  section_num = (n-1) // (layers*cells_on_layer) + 1
  print(f'Место {n} находится в {section_num}-й секции, на {layer_number}-м'\
    f' ярусе.')