# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
e = float(input("Введите e: "))
f = float(input("Введите f: "))
g = float(input("Введите g: "))
h = float(input("Введите h: "))
a = math.sqrt(abs(e - 3/f)**3 + g)
b = math.sin(e) + math.cos(h)**2
c = 33 * g / (e * f - 3)
print("a = %.4f\n" %a,"b = %.4f\n" %b,"c = %.4f" %c, sep='')