# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

a=float(input("Основание трапеции a = "))
b=float(input("Основание трапеции b = "))
h=float(input("Высота трапеции h = "))
s = h * (a + b)/2
print("Площадь трапеции S = %.4f." %s)