# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

import math
a=int(input("Катет a: "))
b=int(input("Катет b: "))
c=math.sqrt(a**2+b**2)
print("Гипотенуза равна %.4f" %c)