# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

n = input("Введите натуральное число, большее 9: ")
if int(n) < 10:
    print("Число должно быть больше 9.")
else:
    # находим количество единиц
    ones = int(n[len(n)-1])
    # находим количество десятков
    tens = int(n[len(n)-2])
    print("Количество единиц:", ones)
    print("Количество десятков:", tens)

