# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmhtubjz2HKP2tK0AfB6zm_F4fHHbCUk
"""

v1=float(input("Скорость первого автомобиля, км/ч: "))
v2=float(input("Скорость второго автомобиля, км/ч: "))
S=float(input("Расстояние между автомобилями, км,  при t=0: "))
t=S /(v1 + v2)
print("Автомобили встретятся через %.2f ч." %t)