# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

# а)
sum = 0
for i in range(200, 601):
  sum += i
mean = sum / 401
print("Сумма чисел от 200 до 600 равна:", sum)
print("Среднее арифметическое чисел от 200 до 600 равно:", mean)

#б)
a = int(input("Введите число a (a<400): "))
if a>=400:
  print(f'{a}>=400!')
else:
  sum = 0
  for i in range(a, 401):
    sum += i
  mean = sum / (401 - a)
  print(f'Сумма чисел от {a} до 400 равна: {sum}')
  print(f'Среднее арифметическое чисел от {a} до 400 равно {mean}')

#в)

b = int(input("Введите число b(b>-15): "))
if b<=-15:
  print(f'{b}<=-15!')
else:
  sum = 0
  for i in range(-15, b+1):
    sum += i
  mean = sum / (b+16)
  print(f'Сумма чисел от -15  до {b} равна: {sum}')
  print(f'Среднее арифметическое чисел от -15 до {b} равно {mean}')

#г)
import math
a = int(input("Введите число a (a>0): "))
if a<=0:
  print("Вы ввели неположительное число!")
else:
  b = int(input("Введите число b (b>a): "))
  if a>=b:
    print(f'{a}>={b}!')
  else:
    sum = 0
    prod = 1
    for i in range(a, b+1):
      sum += i
      prod *=i
    mean_arith = sum / (b-a+1)
    mean_geom = math.pow(prod, 1/(b-1+1))
    print(f'Сумма чисел от {a}  до {b} равна: {sum}')
    print(f'Среднее арифметическое чисел от {a} до {b} равно {mean_arith}')
    print(f'Среднее геометрическое чисел от {a} до {b} равно {mean_geom}')

