# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6uz_hnwdNZcd1tlAJnOVa_o0AtYl1Pi
"""

flats_on_floor=4
n=int(input("Введите номер квартиры: "))
if n>20:
  print("Квартиры с таким номером в подъезде нет")
else:
  floor = (n-1) // flats_on_floor + 1
  number_on_floor = (n-1) % flats_on_floor + 1
  print(f'Квартира {n} находится на {floor}-м, этаже: это {number_on_floor}'\
        '-я по счету квартира.')